---
abstract: 'Provides simple interface to access Yahoo! APIs'
author:
  - 'Satoshi Yagi <satoshi.yagi@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-Yahoo
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::SSLeay: 0
  Data::Dumper: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Net::OAuth: 0
  Test::More: 0
  URI::Escape: 0
  WWW::Mechanize: 0
  YAML::Syck: 0
version: 0.06
