--- #YAML:1.0
name:               Net-OAuth-Yahoo
version:            0.03
abstract:           Provides simple interface to access Yahoo! APIs
author:
    - Satoshi Yagi <satoshi.yagi@yahoo.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:    0
    LWP::UserAgent:  0
    Net::OAuth:      0
    Test::More:      0
    URI::Escape:     0
    WWW::Mechanize:  0
    YAML::Syck:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
